{% set name = "requests-magpie" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bc9a042362421b5cf6de0b4f9b5443f75b550fb818572c5c160c4b671f1a8a04

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit >=3.9,<4.0
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.32.2
test:
  requires:
    - python {{ python_min }}
  imports:
    - requests_magpie

about:
  home: https://github.com/Ouranosinc/Magpie
  license: ISC
  license_family: OTHER
  license_file: LICENSE
  summary: A Magpie authentication handler for python-requests
  dev_url: https://github.com/Ouranosinc/requests-magpie

extra:
  recipe-maintainers:
    - fmigneault
    - Zeitsperre
    - davidcaron
