{% set name = "requests-magpie" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 739e2a29af6d537f70fc30facf319f9cccb0c6501bcfe2bb588f3c63a1ab69b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - requests >=1.1.0

test:
  imports:
    - requests_magpie

about:
  home: https://github.com/Ouranosinc/Magpie
  license: ISC
  license_family: OTHER
  license_file: LICENSE
  summary: A Magpie authentication handler for python-requests
  dev_url: https://github.com/Ouranosinc/requests-magpie

extra:
  recipe-maintainers:
    - fmigneault
    - Zeitsperre
    - davidcaron
